#include "mock_data.hpp"
#include "types/types.hpp"

namespace netbook::mocking {

using netbook::types::IncomingMarketMessage;

// Push mock data to the network controller.
void push_mock_data(std::stop_token stop) {
    while (!stop.stop_requested()) {
        std::this_thread::sleep_for(std::chrono::milliseconds(500));

        char data[] = {"This is sample data generated by a DPDK application ..."};

        netbook::dpdk::push_data(data, sizeof(data));
    }
}

IncomingMarketMessage create_mock_market_data() {

}

}